name: build libsshut

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: prepare
      run: |
        sudo apt-get install -y libevent-dev
        sudo apt-get install -y libssh2-1-dev
        
    - name: make
      run: |
        make && sudo make install
        ./sshut_debug
      
    - name: test
      run: |
        make -C examples/ 
        ldd examples/exec
        echo '*******************'
        ./examples/exec

